Imlemented communication for ViewModels with delegates
deffsin/NotesFS pull request #4
Opened 2023-07-26 13:24 UTC by deffsin

2023-07-27 12:23 UTC, Hassanq911 requested changes

2023-07-27 13:02 UTC, deffsin commented on ViewModel/AddNoteViewModel.swift
> +    weak var delegate: AddNoteViewModelDelegate?
Hmm, this is precautionary measure to prevent a retain cycle even if there isn't one now, it could appear in the future after the adding new functions. In theory we could also use unowned, but it's safer to use weak. Unowned is not safe, like force unwrapping.

2023-07-27 13:03 UTC, deffsin commented on ViewModel/ViewModelDelegates.swift
> +protocol AddNoteViewModelDelegate: AnyObject {
Because we can't use weak or unowned without the AnyObject.
I tried to use these two protocols without the AnyObject and without the "weak" in my ViewModels and i didn't see any difference, in both scenarious everything worked correctly, but i decided to stick to the first scenario when i used AnyObject and weak.

2023-07-27 13:11 UTC, Hassanq911 commented on ViewModel/ViewModelDelegates.swift
> +protocol AddNoteViewModelDelegate: AnyObject {
Hmm can we use class here as well ??

2023-07-27 13:26 UTC, deffsin commented on ViewModel/ViewModelDelegates.swift
> +protocol AddNoteViewModelDelegate: AnyObject {
Do you mean like that??
```
protocol Information {
    var name: String
}

protocol Person: Information {
}

class something: Person {
    var name = "Tom"
}

```

2023-07-27 13:50 UTC, Hassanq911 commented on ViewModel/ViewModelDelegates.swift
> +protocol AddNoteViewModelDelegate: AnyObject {
`protocol AddNoteViewModelDelegate: class`

2023-07-27 13:51 UTC, Hassanq911 requested changes

2023-07-27 13:51 UTC, Hassanq911 commented on ViewModel/ViewModelDelegates.swift
> +    func noteAdded(note: Note)
rename the func to `add(note: Note)` makes more senes this way

2023-07-27 13:51 UTC, Hassanq911 commented on ViewModel/ViewModelDelegates.swift
> +    func noteDelete(note: Note)
rename the func to `delete(note: Note)` makes more senes this way

2023-07-27 14:03 UTC, deffsin commented on ViewModel/ViewModelDelegates.swift
> +protocol AddNoteViewModelDelegate: AnyObject {
Yes, we can. AnyObject and Class equivalent, there is no difference. But usage of class is deprecated, it is better to use AnyObject now.

2023-07-28 09:37 UTC, Hassanq911 approved these changes

2023-07-28 10:47 UTC, merged